nyc_311_project:
  outputs:
    dev:
      type: bigquery
      method: oauth
      # dbt will look for GCP_PROJECT_ID in your .env or system environment
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('DATASET_NAME') }}"
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
  target: dev
